name: Build

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: alaviss/setup-nim@0.1.1
        with:
          path: 'nim'
          version: devel
      - name: Build
        run: |
          nimble install -d -y
          nimble build -d:release -d:ssl
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          type: 'zip'
          filename: dye-linux.zip
          path: dye
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          type: 'zip'
          filename: dye-windows.zip
          path: dye.exe

      - name: Release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["dye-*.zip"]'
